### ISSUE TITLE
Duplicate tags are getting added at document level for a controller class with multiple operations

### ISSUE THREAD

**Issue by bhargavmummini** [youengineering/openapi-maven-plugin#7]
If a tag is added on RestController class which has multiple operations then, those many duplicate tags are added to the openApi document.

For example, 
For the following controller
```
@Tag(name = "Tag Name", description = "Tag Description")
@RestController
public class TestTagController {
    @PostMapping(value = "/test1")
    public SolvencyResponse solvencyValidateLight(){
        ...
    }
    @PostMapping(value = "/test2")
    public void solvencyInitLight() {
        ...
    }
}
```
This is how the generated swagger looks
```
openapi: 3.0.1
info:
  ...
tags:
- name: Tag Name
  description: Tag Description
- name: Tag Name
  description: Tag Description
```

Would suggest to perform an additional check here to add a tag only when there no existing tag with same name.
https://github.com/youengineering/openapi-maven-plugin/blob/2a1cd7d8ac40d3e81161c06871396a2fbcc13003/src/main/java/com/youengineering/openapi/document/reader/AbstractReader.java#L237

**Comment by carlkuesters** [comment]
Hi Barghav,

thanks a lot for reporting this issue and already providing the affected code position. :)

I will release a fixed version today,

Best regards,
Carl

**Comment by carlkuesters** [comment]
I fixed the issue, but there seems to be a problem with Sonatype (https://issues.sonatype.org/browse/OSSRH-68745), so publishing the version timeouts currently. The fix is pushed though (with a testcase) and I will inform you once the new version is available. :)

**Comment by carlkuesters** [comment]
Hi @bhargavmummini,

Sonatype fixed the issue on their side and I could successfully release the version `0.0.11` to Maven Central, which should be available in short time in your artifactory.

Please let me know, if the fix works for you. :)

(Also, for your information: There is currently another issue open (https://github.com/youengineering/openapi-maven-plugin/issues/6), which will result in me upgrading all dependencies of the plugin to the newest version. This will result in the first "real" version `1.0.0` :) (as the plugin is now mature enough). Just for your information, so that you know this will happen soon. Your fix in this issue here is still on the current codebase with the same dependencies, so that we don't break anything accidentally)

Best regards,
Carl

**Comment by bhargavmummini** [comment]
Hi @carlkuesters 

Thanks a lot again for the quick fix.

The fix works great! :) . Closing the issue.

Also thanks for giving an info about the upcoming changes.

Regards,
Bhagrav
